### PR TITLE
Fix broken input.json completion provider

### LINKED ISSUE #1890: No completions from input.json
Doing some work on `main` and not getting any completion suggestions from my `input.json` file.

I have rebuilt Regal, but the issue remains. Other completion providers seem to work as expected. I hope I'm holding it wrong somehow, but it seems like something has broken this provider. If that's the case, we need to have it fixed before the next release.

### PR DESCRIPTION
**Pull request by anderseknert**
Not sure when it happened, but the struct -> ast.Value transform failed to take into account struct field pointing to existing ast.Value values.

Fixes #1890

### CODE REVIEW

File: pkg/roast/rast/rast.go [hunk 1]
```diff
@@ -206,16 +206,21 @@ func StructToValue(input any) ast.Value {
 
 		value := v.Field(i)
 
-		if strings.Contains(tag, ",") {
-			parts := strings.Split(tag, ",")
-			tag = parts[0]
+		if comma := strings.Index(tag, ","); comma != -1 {
```
Comment (srenatus) [inline pkg/roast/rast/rast.go:209]: Looks like a nice place for a strings.Cut 😉

**Review by srenatus — APPROVED** [review]
